### ISSUE TITLE
Update stationary platform icons

### ISSUE THREAD

**Issue by LanesGood** [NASA-IMPACT/admg-casei#655]
In #626 Heidi proposed 7 icons for adding symbology to the stationary platforms on the campaign flight path maps.

These icons were added in #638 and deployed to production. For example, the latest IMPACTS campaign page:
![Screenshot 2024-07-10 at 12 16 30 PM](https://github.com/NASA-IMPACT/admg-casei/assets/12634024/d26f5163-6f3c-487a-ac8a-3ef73c021fef)

Some stylistic changes were made to the icons to better render these on the map:
- Icons are contained within a circle
- Icon circle background features the dark basemap color to provide contrast against the flight path lines
- Icon circle border color matches icon color for greater recognition
- Legend icons are also encircled for consistency

In  https://github.com/NASA-IMPACT/admg-casei/issues/634#issuecomment-2215385416 @smwingo suggests alternative icons for the Field Site and Permanent Land Site platforms:

> Field Site:
> [observation tower icon](https://fontawesome.com/icons/tower-observation?f=classic&s=thin)
> 
> Permanent Land Site:
> [bold obs tower icon](https://fontawesome.com/icons/tower-observation?f=classic&s=regular)

I suggest that for even greater visual identity/uniqueness between the platforms, we use the following for Permanent Land Site:

![Screenshot 2024-07-10 at 12 20 39 PM](https://github.com/NASA-IMPACT/admg-casei/assets/12634024/2e672da7-f949-4a1e-b234-3403c0ea6f67)[house](https://fontawesome.com/icons/house?f=classic&s=solid

I'm also opening this ticket to capture any other feedback on the icons.

Additional solutions to explore to ensure readability:
- Cluster icons on lower zooms
- Hide icon, but keep circle on lower zoom
- Turn off icon-overlap
    - currently icons are permitted to overlap as to not hide any; however, this can be visually messy. the alternative does imply that some icons will be hidden at certain zoom levels to not overlap, which could lead to being missed

**Comment by smwingo** [comment]
gahhh icons are so simple but so hard!!

the other notes you have all sound good, but re: the actual icons....here is an update suggestion list,  please ADMG team leave your thoughts here on this thread also...some of these are the same as before (ie: as on heidi's earlier ticket) some are different, and note that i'm including more options as there are more possible platform types than these initial looks have had:

also @LanesGood is it necessary that we use only the "free" icons? i've marked ones below that are labeled "pro" on the site...with a "free" option that could be used if "pro" is not available....

land platforms:
- permanent field site:
   - https://fontawesome.com/icons/warehouse?f=classic&s=solid
   - https://fontawesome.com/icons/archway?f=classic&s=solid
   - https://fontawesome.com/icons/tower-cell?f=classic&s=solid
- field site:
   - (pro) https://fontawesome.com/icons/tower-observation?f=classic&s=light
   - (free) https://fontawesome.com/icons/tower-broadcast?f=classic&s=solid
   - (free) https://fontawesome.com/icons/compass?f=classic&s=regular
- balloon launch site: 
   - https://fontawesome.com/icons/location-pin?f=classic&s=solid
- vehicle: 
   - https://fontawesome.com/icons/van-shuttle?f=classic&s=solid
- field survey: 
   - https://fontawesome.com/icons/clipboard-list?f=classic&s=solid

water platforms:
- ship/boat:  typically these won't be stationary, but if needed:
   - (pro) https://fontawesome.com/icons/ship?f=classic&s=light
   - (free) https://fontawesome.com/icons/ship?f=classic&s=solid
   - (free) https://fontawesome.com/icons/anchor?f=classic&s=solid
- permanent water site:  
   - https://fontawesome.com/icons/ferry?f=classic&s=solid
- buoys (moored or otherwise,  note that "drifting" buoys might need to be shown as a non-station platform):
   - (pro) https://fontawesome.com/icons/buoy?f=classic&s=solid
   - (free) https://fontawesome.com/icons/monument?f=classic&s=solid

air platforms:
- not stationary so only the color lines is fine

**Comment by EJwalker13** [comment]
This looks good and visually explains what type of field method was conducted during the campaign but needs to follow what platform it is representing. The color contrast is good but just an idea to avoid clutter is potentialy just using the icon without the bubble around it. The color would still contrast on the basemap but it could potentially de-clutter the map. I think the icons would be slimmer if it was just the icon. Also I agree with what Ashlyn said in slack that we should use a radio tower to represent the permenant ground sites. A house could potentially confuse some of the map audience by making them think its a settlement or neighborhood. In  GIS we used the house symbols to represent settlements and neighborhoods. I think we need the symbols to represent the types of platforms that we are trying to visualize.

**Comment by smwingo** [comment]
Ashlyn via Slack:

> I think for the permanent land site I like this [one](https://fontawesome.com/icons/tower-cell?f=classic&s=solid) the best. For the field site, I like this [one](https://fontawesome.com/icons/tower-observation?f=classic&s=thin) or maybe the compass one.

**Comment by rwyatt19** [comment]
I agree with Ashlyn for the [permanent land site option](https://fontawesome.com/icons/tower-cell?f=classic&s=solid). For the field site, I think it's best to avoid a structure since that can convey permanence. The [compass icon](https://fontawesome.com/icons/compass?f=classic&s=regular) could work best. 

I also agree with Eli that it makes sense to connect the icons to platforms as much as possible.

The icons linked for the rest of the land platforms look good to me.

For water platforms, I like [this icon](https://fontawesome.com/icons/ship?f=classic&s=solid) for ship/boat and prefer [this one](https://fontawesome.com/icons/buoy?f=classic&s=solid) for buoys, but it's a pro version icon.

Aesthetically, I think it's best to use icons that are more "filled in" and not just lines because the color & shape will appear more prominently on the map. Eli raises an interesting point about the circle borders. Might be good to try a mock up without the circles just to see what it looks like? I think I would prefer keeping the borders, but would like to see the other option.

**Comment by LanesGood** [comment]
These are all excellent suggestions. I agree with the assertion that the icons should be filled/more solid vs. lineicons for consistency, but other than that I defer to you all on the appropriate linkage between platform and icon.

I've sorted all of the icons mentioned above into a [miro board](https://miro.com/app/board/uXjVKzC1WIo=/?share_link_id=680899632341) for voting. Please vote with one dot per category. You can place your dot next to the icon; the originals are above, and the proposed are below.
![image](https://github.com/user-attachments/assets/5c62b33c-d33e-4c4f-911e-1c618acdd0ae)

I also pasted screenshots in the same miro board of the basemaps featuring icons with versus without a circle background. We added the circle background in development after noting that the flight paths made the icons difficult to distinguish when there were a number of paths and icons overlapping. I would suggest that the background with a border makes the icon more distinguishable.

**Comment by LanesGood** [comment]
And the winners are!

Permanent Land Site: [tower-cell](https://fontawesome.com/icons/tower-cell?f=classic&s=solid)
Vehicles: unchanged
Balloon: unchanged
Field Site: [compass](https://fontawesome.com/icons/compass?f=classic&s=regular)
Field Survey: unchanged
Permanent Water: unchanged
Moored buoy: [buoy](https://fontawesome.com/icons/buoy?f=classic&s=solid)
Ship: [ship](https://fontawesome.com/icons/ship?f=classic&s=solid)

I'll update these icons in the mapbox style and the codebase.
